### PR TITLE
Feature1  added 

### PR DESCRIPTION
**Pull request by Nitin-Ya**
i have added featrur which has multiple file changed

- html 
- css
- file .hs
- 
WhatsApp Image 2023-09-22 at 19 25 43

### CODE REVIEW

**Comment by nitin-pers** [comment]
no added some other lines

**Comment by nitin-pers** [comment]
okat u will added it

**Comment by nitin-pers** [comment]
added it soon

**Comment by nitin-pers** [comment]
sure

**Comment by nitin-pers** [comment]
sas

**Comment by Nitin-Ya** [comment]
comment it
 properly

**Comment by Nitin-Ya** [comment]
added alll the file sreq

**Comment by nitin-pers** [comment]
okay fille addeds

**Pull request merged**
